### ISSUE TITLE
How to use get_mu.py

### ISSUE THREAD

**Issue by jiangyimin123456** [cote3804/JDFT_tools#1]
Dear Cooper,
I am a self-learner of JDFTx software. Your script is very helpful to me. I would like to ask you how to use it correctly and what parameters you need to enter.
I really appreciate for your help, With best wishes.
min

**Comment by cote3804** [comment]
Hello!

I assume you're just asking about get_mu.py. That script takes a voltage defined either in terms of the Standard Hydrogen Electrode (default), which is defined at pH=0, or the Reversible Hydrogen Electrode (using `-r True`) at any pH. If you specify `-r True`, you also need to specify the pH value using `-ph float`.

The way it calculates the `target-mu` tag involves the absolute standard hydrogen potential, which was calibrated for each solvent model. The CANDLE solvent model, which this script defaults to, was calibrated [here]( https://doi.org/10.1063/1.4907731).  

There are some lines that allude to a **jdft_helper.py** script and an inputs file that is read in using `jdft_helper.read_inputs()`. The jdft_helper.py script comes from a different [github repo](https://github.com/Nick-Singstock/BEAST_DB_Manager). If you clone that repo and then store the path to the `manager/` folder in that repo in the environment variable `JDFTx_manager_home`, get_mu.py will be able to use jdft_helper.py to open an inputs file. The inputs file is the standard input tags file my group uses for managing [ASE](https://wiki.fysik.dtu.dk/ase/) and JDFTx input tags. Some default examples can also be found in the gc_manager github repo.

It's worth noting that the jdft_helper.py script is not at all necessary to calculate mu (unless you want a different solvent model than CANDLE). If you want to comment out these lines, the script should still calculate and print the target-mu value to the command line. 
```
gc_manager_path = os.environ['JDFTx_manager_home'] 
#This block looks for the gc_manager path and then 
#appends the path to the active python path so
#that the jdft_helper script functions can be used
sys.path.append(gc_manager_path)
from jdft_helper import helper


bias = args.bias
rhe = args.rhe
pH = args.ph

if os.path.exists('./inputs'):
    with open('./inputs', 'r') as f:
        inputs = f.read()
    # print(inputs.split('\n'))
    inputs = helper().read_inputs('.')
    fluid = inputs['fluid'].strip()
    if fluid == 'LinearPCM':  
        pcm_var = inputs['pcm-variant'].strip()
else:
    print('inputs file not found. Solvent model defaulting to CANDLE')
    fluid = 'LinearPCM'
    pcm_var = 'CANDLE'
```

If you want to use a different solvent model, it would be as easy as adding more argparse arguments. The absolute standard hydrogen potentials are included for many of the JDFTx solvent models within the script, and using them would take some easy logic to specify the `fluid` and `pcm_var` variables.

**Comment by jiangyimin123456** [comment]
Thank you for your informative explanation, which has been extremely valuable to me.
